[project]
name = "repomind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.3.15",
    "langchain-classic>=1.0.8",
    "langchain-community>=0.4.2",
    "langchain-core>=1.5.6",
    "langchain-groq>=1.1.3",
    "langchain-huggingface>=1.2.2",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.2.11",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
]
[project.scripts]
repomind = "repomind.cli:main"

[tool.uv]
package = true
